import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Providers from "@/providers/Providers";
import { Toaster } from "sonner";

const degularDisplay = localFont({
    src: "./../fonts/DegularVariable.ttf",
    weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
    title: "Iris Tour Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${degularDisplay.className} antialiased`}>
                <Providers>{children}</Providers>
                <Toaster
                    toastOptions={{
                        style: {
                            fontSize: "16px",
                        },
                    }}
                    duration={10000}
                    closeButton
                    richColors
                />
            </body>
        </html>
    );
}
