import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import I18nProvider from "@/providers/I18nProvider";

const degularDisplay = localFont({
    src: "./../fonts/DegularVariable.ttf",
    weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
    title: "Iris Tour Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${degularDisplay.className} antialiased`}>
                <I18nProvider>{children}</I18nProvider>
            </body>
        </html>
    );
}
