import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Connexion",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <main className="w-full h-full">{children}</main>;
}
