import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layouts/AppSidebar";
import { cookies } from "next/headers";
import Header from "@/components/layouts/Header";

export const metadata: Metadata = {
    title: "Tableau de bord",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

    return (
        <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <div className="relative w-full h-full">
                <Header />
                <main className="w-full h-full">{children}</main>
            </div>
        </SidebarProvider>
    );
}
